/**
 * This file is generated by a script. Do not edit this file.
 * Last update on 2026-05-27T18:55:48.927Z
 */
import type { UUID } from "node:crypto";

export interface QuizzemDto {
  id: UUID;
  createdAt: Date;
  updatedAt: Date | null;
}

export interface AnswerDto extends QuizzemDto {
  text: string;
}

export interface QuestionDto extends QuizzemDto {
  text: string;
  type: QuestionType;
  correctAnswer: string;
  answers: AnswerDto[];
}

export interface CreateGameDto {
  title: string;
  description: string | null;
}

export interface GameDto extends QuizzemDto {
  state: GameState;
  title: string | null;
  description: string | null;
  questions: QuestionDto[];
}
