import { join } from "node:path";
import {
  type EnumDeclarationStructure,
  type InterfaceDeclarationStructure,
  type OptionalKind,
  Project,
  type PropertySignatureStructure,
  type SourceFile,
  StructureKind,
} from "ts-morph";

// Paths
const rootDir = join(process.cwd(), "..", "backend");
const outputFilePath = join(
  process.cwd(),
  "src",
  "__generated__",
  "generated.ts",
);

// Helper function to find .ts files in dto folders
function getDtoOrEnumFiles(
  sourceFiles: SourceFile[],
  fileType: "dto" | "enum",
): SourceFile[] {
  return sourceFiles.filter((file) => file.getFilePath().includes(fileType));
}

// Function to map types (e.g., replace id's type with 'UUID')
function mapPropertyType(type: string): string {
  if (type === "`${string}-${string}-${string}-${string}-${string}`") {
    return "UUID";
  }
  return type;
}

// main function to generate the file
async function main() {
  // set up the project and declare the classDefinitions array
  const project = new Project({
    tsConfigFilePath: join(rootDir, "tsconfig.json"),
  });

  const interfaceDefinitions: InterfaceDeclarationStructure[] = [];
  const enumDefinitions: EnumDeclarationStructure[] = [];

  // specify the source files to be used
  project.addSourceFilesAtPaths(`${rootDir}/src/**/*.ts`);
  const dtoFiles = getDtoOrEnumFiles(project.getSourceFiles(), "dto");
  const enumFiles = getDtoOrEnumFiles(project.getSourceFiles(), "enum");

  console.log(
    `Found ${dtoFiles.length} DTO files and ${enumFiles.length} Enum files.`,
  );

  // Create the source file and add the comment
  const sourceFile = project.createSourceFile(
    outputFilePath,
    `/**
   * This file is generated by a script. Do not edit this file.
   * Last update on ${new Date().toISOString()}
   */
   `,
    { overwrite: true },
  );

  // Add the crypto import at the top of the file
  sourceFile.addImportDeclaration({
    moduleSpecifier: "node:crypto",
    namedImports: ["UUID"],
    isTypeOnly: true,
  });

  // Loop through the dto files and classes to generate the class definitions
  for (const file of dtoFiles) {
    console.log(`Processing DTO file: ${file.getBaseName()}`);

    const classes = file.getClasses();

    for (const cls of classes) {
      const extendsClause = cls.getExtends()?.getText();
      const interfaceStructure: InterfaceDeclarationStructure = {
        kind: StructureKind.Interface,
        name: cls.getName()!,
        isExported: true,
        typeParameters: cls.getTypeParameters().map((tp) => tp.getText()),
        ...(extendsClause && { extends: [extendsClause] }),
        properties: cls.getProperties().map((prop) => {
          const typeText = mapPropertyType(prop.getType().getText());
          return {
            name: prop.getName(),
            hasQuestionToken: prop.hasQuestionToken(),
            type: typeText.startsWith("import(")
              ? (typeText.split(".").pop() ?? typeText)
              : typeText,
          } as OptionalKind<PropertySignatureStructure>;
        }),
      };
      interfaceDefinitions.push(interfaceStructure);
    }
  }

  for (const file of enumFiles) {
    console.log(`Processing Enum file: ${file.getBaseName()}`);

    const enums = file.getEnums();
    for (const enm of enums) {
      const enumStructure: EnumDeclarationStructure = {
        kind: StructureKind.Enum,
        name: enm.getName(),
        isExported: true,
        members: enm.getMembers().map((member) => ({
          name: member.getName(),
          value: member.getValue(),
        })),
      };
      enumDefinitions.push(enumStructure);
    }
  }

  // Add the class definitions to the source file
  for (const interfaceDefinition of interfaceDefinitions) {
    sourceFile.addInterface(interfaceDefinition);
  }
  for (const enumDefinition of enumDefinitions) {
    sourceFile.addEnum(enumDefinition);
  }

  sourceFile.saveSync();
}

main().catch(console.error);
