export enum EGameRoundType {
  STANDARD_QUIZ_ROUND = 'STANDARD_QUIZ_ROUND',
  SPEED_QUIZ_ROUND = 'SPEED_QUIZ_ROUND',
  ACTION_ROUND = 'ACTION_ROUND',
  MEDIA_ROUND = 'MEDIA_ROUND',
  BONUS_ROUND = 'BONUS_ROUND',
  BUZZ_ROUND = 'BUZZ_ROUND',
  // CUSTOM_ROUND = "CUSTOM_ROUND",
}
