/**
       * This file is generated by a script. Do not edit this file.
       * Last update on 2025-07-24T19:20:07.616Z
       */
import type { UUID } from "crypto";

export interface QuizzemDto {
    id: UUID;
    createdAt: Date;
}

export interface SignInDto {
    userName: string;
    password: string;
}

export interface SignUpDto {
    userName: string;
    password: string;
}

export interface TokenPayloadDto {
    accessToken: string;
}

export interface CreateQuestionDto {
    question: string;
    questionType: QuestionType;
    correctAnswer: string | number | boolean;
    answers?: string | undefined;
}

export interface QuestionDto extends QuizzemDto {
    question: string;
    questionType: string;
    correctAnswer: string;
    answers: string | null;
}

export interface CreateUserDto {
    userName: string;
    password: string;
}

export interface UpdateUserDto {
    userName?: string | undefined;
}

export interface UserDto extends QuizzemDto {
    userName: string;
}

export interface PageableQueryDto {
    page: number;
    size: number;
}

export interface PageableDto<T> {
    data: T[];
    page: number;
    totalPages: number;
    size: number;
    totalElements: number;
}

export enum QuestionType {
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
    TRUE_FALSE = "TRUE_FALSE",
    FILL_IN_THE_BLANK = "FILL_IN_THE_BLANK",
    ORDERING = "ORDERING",
    ESTIMATE = "ESTIMATE",
    NUMERIC = "NUMERIC",
    IMAGE_QUESTION = "IMAGE_QUESTION",
    MUSIC_QUESTION = "MUSIC_QUESTION",
    VIDEO_QUESTION = "VIDEO_QUESTION"
}
       